version: '3.7'
services:
  postgresql:
    image: postgres
    restart: always
    volumes:
    - ./pg_data:/var/lib/postgresql/data:rw
    environment:
    - ./db.env
    ports:
    - 5432:5432
  django:
    env_file:
      - ./app.env
    build: ./
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgresql