# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-07-31 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.CharField(max_length=512)),
                ('shortened_url', models.CharField(max_length=255)),
                ('counter', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Url Shortener',
                'verbose_name_plural': 'Url Shorteners',
            },
        ),
    ]
